### ISSUE TITLE
won't build on Mac OS X

### ISSUE THREAD

**Issue by joe-jordan** [aewallin/openvoronoi#10]
I get a build error.

Cmake runs without issue (well, it gave me warnings about missing libraries, I installed them, then it ran with out issue).

Then, upon running "make", the static library builds find and the dynamic passes clang an invalid combination of parameters:

```
[ 95%] Built target openvoronoi_static
Scanning dependencies of target openvoronoi
[100%] Building CXX object CMakeFiles/openvoronoi.dir/py/open_voronoi_py.o
Linking CXX shared module openvoronoi.so
clang: error: invalid argument '-current_version 12.2.284' only allowed with '-dynamiclib'
make[2]: *** [openvoronoi.12.02.284.so] Error 1
make[1]: *** [CMakeFiles/openvoronoi.dir/all] Error 2
make: *** [all] Error 2
```

I am not a cmake expert, so I don't know how to edit/re-run with the updated option added - instructions on how to do that would be very helpful, as well as a patch!

My system details are:

Mac OS X 10.8.3, clang:

```
Apple LLVM version 4.2 (clang-425.0.24) (based on LLVM 3.2svn)
Target: x86_64-apple-darwin12.3.0
Thread model: posix
```

System python (2.7.3, framework.)

**Comment by aewallin** [comment]
closing this old issue.
