### ISSUE TITLE
change "print get_python_lib()" to "print(get_python_lib())" in CMakeLists.txt

### ISSUE THREAD

**Issue by esigra** [aewallin/openvoronoi#30]
I had to change "print get_python_lib()" to "print(get_python_lib())" in CMakeLists.txt so that cmake would complete.

(I am trying to use openvoronoi to construct land ownership borders according to jordabalken 1 kap. 5 §, see [https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/jordabalk-1970994_sfs-1970-994#K1].)

**Comment by aewallin** [comment]
I committed this change. closing issue.
