### ISSUE TITLE
Consider changing to more permissive license

### ISSUE THREAD

**Issue by sliptonic** [aewallin/openvoronoi#35]
The GPL3 license with strong copyleft provisions is too restrictive to allow linking and packaging with applications like FreeCAD that are LGPL.

If openvoronoi was re-licensed LGPL2.1, inclusion in other applications would be easier and interest in using the library would increase.

I'm willing to help with any re-licensing effort and FreeCAD community will help with debian packaging if re-licensed so we can use it.

**Comment by aewallin** [comment]
To me a change to LGPL2.1 is OK.

This page lists 5 more (minor) contributors to the codebase - maybe we could get an "ok" from them in this thread just to be on the safe side before a license change.
https://github.com/aewallin/openvoronoi/graphs/contributors

in addition there are probably many forks with enhancements that haven't been merged back to my repo - but I haven't heard of any major developments...

**Comment by Rogach** [comment]
OK

**Comment by gavanderhoorn** [comment]
I'm ok with re-licensing to lgpl or a more permissive license.

**Comment by VictorLamoine** [comment]
I'm ok with re-licensing to lgpl or a more permissive license.

**Comment by Blokkendoos** [comment]
I'm ok with LGPL or a more permissive license.

**Comment by aewallin** [comment]
Thanks for quick replies everyone!

What would be the preferred workflow for this? I could imagine:
- tag the current version "GPL2018.07" as the last with the old license
- do the license change in all files where GPL is mentioned (maybe some automation here?)
- tag a new version as 2018.08 (or similar) using LGPL

**Comment by sliptonic** [comment]
That sounds good to me.  The license header change is probably a solved problem.  Maybe here: https://github.com/johann-petrak/licenseheaders

**Comment by aewallin** [comment]
The proposed change to LGPL 2.1 is now in a branch called "LGPL".
I will try to go through most non-trivial c++/python files and check the headers in the next few days.
If there are no objections I will then merge LGPL into master.

**Comment by aewallin** [comment]
I merged the LGPL branch into master. (pull request #40 )
Thanks for the help with changing the license.
closing this issue now.

**Comment by kkremitzki** [comment]
@aewallin Can you tag a release with a bumped version number, preferably one that is greater than current existing tags? (i.e. since there's a tag that starts with version "2018...", tagging 18.07 or 18.08 would not be ideal since version comparison tools would think version 18.x < version 2018.x)

**Comment by aewallin** [comment]
2018.08 now tagged, from master.
