### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by kkremitzki** [aewallin/openvoronoi#39]
Hi, I've more or less completed the work of packaging OpenVoronoi for Debian in preparation for the relicensing. It's possible to automatically provide both Python 2 & 3 packages, but it looks like Python 3 is not supported. I crossed my fingers and tried it after replacing all the `print `s with `print()`s, but it looks like it'll be slightly more effort than that. Have you given any thought to adding Python 3 support?

**Comment by aewallin** [comment]
Python 3 compatibility sounds like a good idea - I guess in the far future distributions will drop python 2 eventually.

For another (pure python) project I am running tests with different python versions (2.7, 3.4, 3.5, 3.6) with travis. I wonder if we could have two travis-runs set up, one for the C++ build and tests, and another for the python tests?

I don't know what to do about the python-code that is not in tests. Probably these need to be run and debugged manually from time to time.

**Comment by luzpaz** [comment]
Think this is a priority since distros will soon be phasing out non-py3 packages from their 'testing' branches.

**Comment by aewallin** [comment]
should work now, closing.
