### ISSUE TITLE
insert_point_site fail

### ISSUE THREAD

**Issue by trlsmax** [aewallin/openvoronoi#50]
I try to build the cpp example on win10 with vs2019. build ok, but even insert first point site made program crash.
In medial axis example, it failed at line 27:
`int id0 = vd->insert_point_site(p0);`
![image](https://user-images.githubusercontent.com/5501321/122180481-0ac7bb00-cebb-11eb-8879-87c10b694dde.png)

Is that openvoronoi is not support windows? Or I use the wrong version of boost ?

**Comment by vespakoen** [comment]
I got the same on macOS (running any of the tests)

I wonder if it works on Linux since in CI things seem to work fine.

<img width="1221" alt="Screenshot 2022-12-15 at 17 06 50" src="https://user-images.githubusercontent.com/876117/207919426-fd4432b3-9181-42c8-bdd1-d157ae9b1e94.png">

**Comment by vespakoen** [comment]
I can confirm that it works correctly on linux, and it seems to be caused by this line:

https://github.com/aewallin/openvoronoi/blob/master/src/common/halfedgediagram.hpp#L277

When that is commented out, things >seem< to work. perhaps @aewallin can tell us more with that hint?

**Comment by aewallin** [comment]
Does macOS always use Clang as the compiler? gcc vs. clang could be tested on linux also.
I can try to take a look at some point - but it's years since I worked with this code seriously..

**Comment by aewallin** [comment]
now merged. but I probably won't have time to test in the next week or so..

**Comment by mmassing** [comment]
Thanks!
